# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: themesync
version: '0.1'
author: 'Stefan Beyer'
supportpage: 
info: ''
compile: 0

page:
    title: 'translate:title'
    perm: themesync[]
    icon: rex-icon fa-plus-square
    pjax: false
    subpages:
        sync:
            title: 'Sync'
        config:
            title: 'Config'
        info:
            title: 'Info'
            itemclass: 'pull-right'
            subpages:
                info: { title: 'Info'}
                changelog: { title: 'translate:changelog'}
                lizenz: { title: 'translate:lizenz'}